INSERT INTO customer VALUES('ryan.combs@gmail.com', 'Ryan Combs', '5187 Park Rd, A3R 4E4, Canada');
INSERT INTO customer VALUES('ahmad.espinoza@hotmail.com', 'Ahmad Espinoza', '7548 Grand Marais Ave, L9B 0E0, Canada');
INSERT INTO customer VALUES('lucille.klein@yahoo.ca', 'Lucille Klein', '7216 9th St, H8D 2T4, Canada');
INSERT INTO customer VALUES('marco.salazar@hotmail.com', 'Marco Salazar', '9907 22nd Ave, R6R 6N2, Canada');
INSERT INTO customer VALUES('freya.taylor@hotmail.com', 'Freya Taylor', '9117 Dalhousie Ave, W2P 3L0, Canada');
INSERT INTO customer VALUES('jackson.ross@gmail.com', 'Jackson Ross', '2226 Concession Road 6, L1M 3N4, Canada');
INSERT INTO customer VALUES('peyton.quintana@yahoo.ca', 'Peyton Quintana', '3069 Concession Road 6, I2D 4C8, Canada');
INSERT INTO customer VALUES('kelvin.gilmore@yahoo.ca', 'Kelvin Gilmore', '5129 George St, D6K 3F8, Canada');
INSERT INTO customer VALUES('chanel.avery@hotmail.com', 'Chanel Avery', '5725 22nd Ave, E9Y 4Q0, Canada');
INSERT INTO customer VALUES('jakari.o’connell@gmail.com', 'Jakari O’Connell', '959 15th St, A7U 2D6, Canada');
INSERT INTO customer VALUES('jillian.jaramillo@hotmail.com', 'Jillian Jaramillo', '6305 Grand Ave, A0Q 8S0, Canada');
INSERT INTO customer VALUES('riggs.o’neill@hotmail.com', 'Riggs O’Neill', '1365 George St, G1Y 2E8, Canada');
INSERT INTO customer VALUES('kenna.pittman@gmail.com', 'Kenna Pittman', '5841 Main St, Q5P 9J8, Canada');
INSERT INTO customer VALUES('valentino.hopkins@hotmail.com', 'Valentino Hopkins', '2119 Richmond Ave, K7D 2J1, Canada');
INSERT INTO customer VALUES('gabriela.shelton@hotmail.com', 'Gabriela Shelton', '3346 15th St, D3Q 4B3, Canada');
INSERT INTO customer VALUES('leonel.stevenson@gmail.com', 'Leonel Stevenson', '5780 Argyle St, T7E 1Y0, Canada');
INSERT INTO customer VALUES('regina.blair@yahoo.ca', 'Regina Blair', '7003 Duke St, V4H 5Y9, Canada');
INSERT INTO customer VALUES('troy.wyatt@hotmail.com', 'Troy Wyatt', '5108 Bay Ave, S1S 7G7, Canada');
INSERT INTO customer VALUES('liberty.choi@gmail.com', 'Liberty Choi', '3811 Oak St, X8O 5M2, Canada');
INSERT INTO customer VALUES('khari.friedman@yahoo.ca', 'Khari Friedman', '7333 College Ave, P2S 2O4, Canada');
INSERT INTO customer VALUES('aspyn.rios@hotmail.com', 'Aspyn Rios', '1135 Concession Road 6, W5Q 8F3, Canada');
INSERT INTO customer VALUES('israel.higgins@hotmail.com', 'Israel Higgins', '2407 Arctic Way, D7J 5T0, Canada');
INSERT INTO customer VALUES('leighton.hammond@yahoo.ca', 'Leighton Hammond', '3025 3rd St, P4D 2X5, Canada');
INSERT INTO customer VALUES('francis.horne@hotmail.com', 'Francis Horne', '7168 Coastal Highway, R2V 6I8, Canada');
INSERT INTO customer VALUES('marlowe.valencia@yahoo.ca', 'Marlowe Valencia', '7884 Simcoe St, T3A 0T4, Canada');
INSERT INTO customer VALUES('dax.lugo@gmail.com', 'Dax Lugo', '4630 Argyle St, D7B 3V8, Canada');
INSERT INTO customer VALUES('kaylie.atkinson@hotmail.com', 'Kaylie Atkinson', '1958 Coastal Highway, I7X 4P7, Canada');
INSERT INTO customer VALUES('duke.higgins@gmail.com', 'Duke Higgins', '6872 Cedar St, Q9Q 5X9, Canada');
INSERT INTO customer VALUES('leighton.pacheco@gmail.com', 'Leighton Pacheco', '7212 Wellington St, P4T 9L9, Canada');
INSERT INTO customer VALUES('erik.mckenzie@yahoo.ca', 'Erik McKenzie', '6341 9th St, W1Q 9L0, Canada');
INSERT INTO customer VALUES('briar.contreras@hotmail.com', 'Briar Contreras', '4912 Pierre Ave, F7Y 7C2, Canada');
INSERT INTO customer VALUES('emilio.kaur@gmail.com', 'Emilio Kaur', '7815 Lakeview Ave, Y7C 6J3, Canada');
INSERT INTO customer VALUES('holland.freeman@yahoo.ca', 'Holland Freeman', '4956 Tecumseh Rd, I2D 3R8, Canada');
INSERT INTO customer VALUES('jayce.rich@gmail.com', 'Jayce Rich', '5815 Arctic Way, Y9D 7G4, Canada');
INSERT INTO customer VALUES('sunny.burch@gmail.com', 'Sunny Burch', '9875 Pierre Ave, G5L 3J5, Canada');
INSERT INTO customer VALUES('gerald.brock@yahoo.ca', 'Gerald Brock', '669 Dundas Rd, Z2X 2W0, Canada');
INSERT INTO customer VALUES('jada.ingram@gmail.com', 'Jada Ingram', '9998 36th Ave, A5L 9D8, Canada');
INSERT INTO customer VALUES('tripp.prince@yahoo.ca', 'Tripp Prince', '6087 Grand Ave, K4C 9W6, Canada');
INSERT INTO customer VALUES('greta.mata@gmail.com', 'Greta Mata', '9844 Elgin St, I4R 5A7, Canada');
INSERT INTO customer VALUES('ray.fuller@gmail.com', 'Ray Fuller', '669 Brock Rd, E8B 6Z3, Canada');
INSERT INTO customer VALUES('oakley.gardner@yahoo.ca', 'Oakley Gardner', '5070 Peel St, M1W 1X9, Canada');
INSERT INTO customer VALUES('alan.cobb@yahoo.ca', 'Alan Cobb', '6271 College Ave, G0V 1C8, Canada');
INSERT INTO customer VALUES('aviana.armstrong@yahoo.ca', 'Aviana Armstrong', '9002 Duke St, F4N 7Z4, Canada');
INSERT INTO customer VALUES('grant.beard@yahoo.ca', 'Grant Beard', '8806 St. Catherine St, P3A 8K6, Canada');
INSERT INTO customer VALUES('ezra.russo@yahoo.ca', 'Ezra Russo', '1411 Queen St, Q0W 2T3, Canada');
INSERT INTO customer VALUES('jamie.aguilar@yahoo.ca', 'Jamie Aguilar', '4727 Pierre Ave, D9I 3S6, Canada');
INSERT INTO customer VALUES('josie.saunders@yahoo.ca', 'Josie Saunders', '7439 36th Ave, X8L 4P1, Canada');
INSERT INTO customer VALUES('kasen.may@hotmail.com', 'Kasen May', '6590 Bay Ave, W4W 7W8, Canada');
INSERT INTO customer VALUES('adriana.anthony@yahoo.ca', 'Adriana Anthony', '949 Maple Ave, B2K 2I1, Canada');
INSERT INTO customer VALUES('shiloh.escobar@hotmail.com', 'Shiloh Escobar', '7213 Tecumseh Rd, H1K 0D7, Canada');
INSERT INTO customer VALUES('erin.sanders@hotmail.com', 'Erin Sanders', '80 Grand Ave, X1C 8V3, Canada');
INSERT INTO customer VALUES('jose.gray@yahoo.ca', 'Jose Gray', '5683 Coastal Highway, G9Q 1K4, Canada');
INSERT INTO customer VALUES('sarah.montgomery@hotmail.com', 'Sarah Montgomery', '8608 Lakeview Ave, P3D 0M6, Canada');
INSERT INTO customer VALUES('maximiliano.huber@yahoo.ca', 'Maximiliano Huber', '1667 Victoria Ave, Z9U 8Y0, Canada');
INSERT INTO customer VALUES('raquel.lee@gmail.com', 'Raquel Lee', '1669 George St, U3Q 4O9, Canada');
INSERT INTO customer VALUES('jack.castro@yahoo.ca', 'Jack Castro', '2487 Parliament St, N0L 6B5, Canada');
INSERT INTO customer VALUES('eloise.hudson@hotmail.com', 'Eloise Hudson', '4154 15th St, H4N 1J4, Canada');
INSERT INTO customer VALUES('peter.rangel@yahoo.ca', 'Peter Rangel', '9964 Grand Ave, Y9J 8A9, Canada');
INSERT INTO customer VALUES('gloria.lynch@hotmail.com', 'Gloria Lynch', '4972 Arctic Way, R3H 9X6, Canada');
INSERT INTO customer VALUES('zane.frye@gmail.com', 'Zane Frye', '7423 Stanley Way, L9Z 1C4, Canada');
INSERT INTO customer VALUES('raya.jaramillo@hotmail.com', 'Raya Jaramillo', '5616 Coastal Highway, W1G 9J1, Canada');
INSERT INTO customer VALUES('riggs.mcclain@hotmail.com', 'Riggs McClain', '1968 Lakeview Ave, Z7J 0D2, Canada');
INSERT INTO customer VALUES('marleigh.kemp@gmail.com', 'Marleigh Kemp', '7631 Tecumseh Rd, J1F 8R1, Canada');
INSERT INTO customer VALUES('melvin.hobbs@gmail.com', 'Melvin Hobbs', '8796 Tecumseh Rd, E1A 4A6, Canada');
INSERT INTO customer VALUES('lacey.delgado@gmail.com', 'Lacey Delgado', '5370 Argyle St, X8T 1Z5, Canada');
INSERT INTO customer VALUES('colt.moran@yahoo.ca', 'Colt Moran', '4455 Victoria Ave, I7B 9B5, Canada');
INSERT INTO customer VALUES('celeste.dominguez@gmail.com', 'Celeste Dominguez', '5260 Maple Ave, B2V 7P2, Canada');
INSERT INTO customer VALUES('kaden.donovan@yahoo.ca', 'Kaden Donovan', '4065 Maple Ave, S2J 8I8, Canada');
INSERT INTO customer VALUES('azariah.santos@hotmail.com', 'Azariah Santos', '543 Arctic Way, V9B 2D3, Canada');
INSERT INTO customer VALUES('walker.skinner@yahoo.ca', 'Walker Skinner', '3079 Vimy St, A0X 8L0, Canada');
INSERT INTO customer VALUES('mara.parks@gmail.com', 'Mara Parks', '4442 Grand Marais Ave, D6X 0W0, Canada');
INSERT INTO customer VALUES('gianni.archer@hotmail.com', 'Gianni Archer', '8626 Elgin St, O6V 1X4, Canada');
INSERT INTO customer VALUES('kadence.savage@yahoo.ca', 'Kadence Savage', '6855 Pierre Ave, S1Y 4R6, Canada');
INSERT INTO customer VALUES('keaton.ashley@hotmail.com', 'Keaton Ashley', '2843 Frederick Ave, M9N 9X7, Canada');
INSERT INTO customer VALUES('khalani.hebert@yahoo.ca', 'Khalani Hebert', '2932 Grand Ave, D8W 8C2, Canada');
INSERT INTO customer VALUES('guillermo.gates@yahoo.ca', 'Guillermo Gates', '1364 Tecumseh Rd, Z5J 2P7, Canada');
INSERT INTO customer VALUES('melina.lindsey@gmail.com', 'Melina Lindsey', '1919 St. Lawrence Ave, F9Q 9G8, Canada');
INSERT INTO customer VALUES('jayson.hernandez@yahoo.ca', 'Jayson Hernandez', '7730 St. Lawrence Ave, Z6E 3Y4, Canada');
INSERT INTO customer VALUES('camila.luna@hotmail.com', 'Camila Luna', '8 Vimy St, N8D 0W1, Canada');
INSERT INTO customer VALUES('erick.potter@yahoo.ca', 'Erick Potter', '4698 Peel St, I0P 8C5, Canada');
INSERT INTO customer VALUES('rory.gomez@gmail.com', 'Rory Gomez', '3561 Dalhousie Ave, K1P 6B3, Canada');
INSERT INTO customer VALUES('isaiah.michael@yahoo.ca', 'Isaiah Michael', '2335 Alfred St, R1Y 6W9, Canada');
INSERT INTO customer VALUES('aubriella.hogan@hotmail.com', 'Aubriella Hogan', '9361 Pine Rd, O3C 8E4, Canada');
INSERT INTO customer VALUES('sonny.bradford@gmail.com', 'Sonny Bradford', '6886 Dieppe Ave, O4H 4Q5, Canada');
INSERT INTO customer VALUES('rhea.meadows@gmail.com', 'Rhea Meadows', '1193 Frederick Ave, B3Q 4D8, Canada');
INSERT INTO customer VALUES('wayne.mccoy@yahoo.ca', 'Wayne McCoy', '1613 Pierre Ave, Q0S 5Z4, Canada');
INSERT INTO customer VALUES('mckenzie.miranda@gmail.com', 'Mckenzie Miranda', '969 9th St, R0B 5O7, Canada');
INSERT INTO customer VALUES('rory.strickland@gmail.com', 'Rory Strickland', '9011 Maple Ave, F0B 1Q9, Canada');
INSERT INTO customer VALUES('nia.sparks@gmail.com', 'Nia Sparks', '4480 Balmoral St, O9C 0Q6, Canada');
INSERT INTO customer VALUES('drake.fields@hotmail.com', 'Drake Fields', '9099 Dundas Rd, I8C 3I1, Canada');
INSERT INTO customer VALUES('annie.middleton@gmail.com', 'Annie Middleton', '6506 3rd St, F1M 6T6, Canada');
INSERT INTO customer VALUES('misael.hanson@gmail.com', 'Misael Hanson', '7914 15th St, P7C 3S6, Canada');
INSERT INTO customer VALUES('mariana.choi@gmail.com', 'Mariana Choi', '9133 York St, N2N 3C5, Canada');
INSERT INTO customer VALUES('khari.noble@yahoo.ca', 'Khari Noble', '3819 Dufferin St, Q4T 6T9, Canada');
INSERT INTO customer VALUES('hunter.finley@hotmail.com', 'Hunter Finley', '566 Arctic Way, Z8I 0Y6, Canada');
INSERT INTO customer VALUES('calum.leon@gmail.com', 'Calum Leon', '797 Charles St, V5X 2T8, Canada');
INSERT INTO customer VALUES('amora.knox@gmail.com', 'Amora Knox', '1075 Oak St, X2L 0B5, Canada');
INSERT INTO customer VALUES('valentin.terrell@gmail.com', 'Valentin Terrell', '4118 Coastal Highway, V9L 4N9, Canada');
INSERT INTO customer VALUES('paityn.middleton@gmail.com', 'Paityn Middleton', '2041 Park Rd, J5S 4Z6, Canada');
INSERT INTO customer VALUES('misael.fields@hotmail.com', 'Misael Fields', '1124 Tecumseh Rd, B7O 6P4, Canada');
INSERT INTO customer VALUES('annie.mcconnell@yahoo.ca', 'Annie McConnell', '397 Grand Ave, V4R 5F9, Canada');
INSERT INTO customer VALUES('london.holland@yahoo.ca', 'London Holland', '3496 St. Lawrence Ave, H7E 4M4, Canada');
INSERT INTO customer VALUES('mariah.deleon@yahoo.ca', 'Mariah Deleon', '138 St. Catherine St, H5N 8L6, Canada');
INSERT INTO customer VALUES('nasir.hinton@hotmail.com', 'Nasir Hinton', '10 9th St, B6Y 5M9, Canada');
INSERT INTO customer VALUES('jaelynn.craig@yahoo.ca', 'Jaelynn Craig', '2776 Wellington St, E6T 2H9, Canada');
INSERT INTO customer VALUES('odin.wyatt@gmail.com', 'Odin Wyatt', '8379 Brock Rd, T9P 8M3, Canada');
INSERT INTO customer VALUES('liberty.mays@gmail.com', 'Liberty Mays', '514 Pine Rd, D6K 4L1, Canada');
INSERT INTO customer VALUES('jadiel.singleton@yahoo.ca', 'Jadiel Singleton', '1709 Peel St, D4T 3V7, Canada');
INSERT INTO customer VALUES('malaysia.gallagher@yahoo.ca', 'Malaysia Gallagher', '3804 Alfred St, F6J 9L3, Canada');
INSERT INTO customer VALUES('marcos.maynard@hotmail.com', 'Marcos Maynard', '7212 Lakeview Ave, J3J 9F5, Canada');
INSERT INTO customer VALUES('carolyn.pope@hotmail.com', 'Carolyn Pope', '8557 Coastal Highway, D6E 6D1, Canada');
INSERT INTO customer VALUES('gunnar.velez@hotmail.com', 'Gunnar Velez', '2225 Stanley Way, H4X 7E4, Canada');
INSERT INTO customer VALUES('megan.corona@gmail.com', 'Megan Corona', '2996 Dieppe Ave, I4S 8J4, Canada');
INSERT INTO customer VALUES('darian.martin@hotmail.com', 'Darian Martin', '4732 Vimy St, Y0T 7T9, Canada');
INSERT INTO customer VALUES('mila.schroeder@yahoo.ca', 'Mila Schroeder', '8758 Oak St, T9B 5X8, Canada');
INSERT INTO customer VALUES('izaiah.felix@gmail.com', 'Izaiah Felix', '430 Dieppe Ave, U9M 1K8, Canada');
INSERT INTO customer VALUES('paisleigh.allison@hotmail.com', 'Paisleigh Allison', '6868 15th St, C3M 5Y2, Canada');
INSERT INTO customer VALUES('dennis.gregory@gmail.com', 'Dennis Gregory', '3319 Main St, Y5D 3J9, Canada');
INSERT INTO customer VALUES('alaya.dougherty@yahoo.ca', 'Alaya Dougherty', '3791 9th St, X3S 2F7, Canada');
INSERT INTO customer VALUES('brett.meyers@hotmail.com', 'Brett Meyers', '9186 9th St, Y1Q 7T9, Canada');
INSERT INTO customer VALUES('leyla.cole@gmail.com', 'Leyla Cole', '507 Dufferin St, M3C 0U4, Canada');
INSERT INTO customer VALUES('nathaniel.rodriguez@hotmail.com', 'Nathaniel Rodriguez', '3375 Concession Road 23, B0C 6W2, Canada');
INSERT INTO customer VALUES('evelyn.barber@yahoo.ca', 'Evelyn Barber', '3107 Pine Rd, N3G 2T9, Canada');
INSERT INTO customer VALUES('solomon.vaughn@gmail.com', 'Solomon Vaughn', '3986 Wellington St, W8E 7H7, Canada');
INSERT INTO customer VALUES('reign.becker@gmail.com', 'Reign Becker', '1348 Duke St, E3Q 9H6, Canada');
INSERT INTO customer VALUES('lawson.anderson@gmail.com', 'Lawson Anderson', '8832 Duke St, K9N 4P5, Canada');
INSERT INTO customer VALUES('ella.allison@yahoo.ca', 'Ella Allison', '8692 Cedar St, W7W 0K1, Canada');
INSERT INTO customer VALUES('dennis.o’brien@gmail.com', 'Dennis O’brien', '1253 Duke St, V6J 3C4, Canada');
INSERT INTO customer VALUES('joanna.villegas@hotmail.com', 'Joanna Villegas', '7330 Coastal Highway, C7D 7N1, Canada');
INSERT INTO customer VALUES('clyde.ashley@gmail.com', 'Clyde Ashley', '1518 Coastal Highway, B5X 2Z3, Canada');
INSERT INTO customer VALUES('khalani.fischer@yahoo.ca', 'Khalani Fischer', '8219 Main St, O4M 8T7, Canada');
INSERT INTO customer VALUES('leonidas.jordan@gmail.com', 'Leonidas Jordan', '7255 Main St, L9P 4E1, Canada');
INSERT INTO customer VALUES('adalynn.deleon@gmail.com', 'Adalynn Deleon', '4864 Alfred St, R4N 9J9, Canada');
INSERT INTO customer VALUES('nasir.butler@hotmail.com', 'Nasir Butler', '8477 Tecumseh Rd, P1F 1D1, Canada');
INSERT INTO customer VALUES('athena.suarez@hotmail.com', 'Athena Suarez', '8024 Lake of Bays Road, K8W 4C9, Canada');
INSERT INTO customer VALUES('soren.gordon@yahoo.ca', 'Soren Gordon', '3139 Pine Rd, C5E 3X5, Canada');
INSERT INTO customer VALUES('taylor.nixon@hotmail.com', 'Taylor Nixon', '2399 22nd Ave, M3H 6Y6, Canada');
INSERT INTO customer VALUES('cory.hansen@gmail.com', 'Cory Hansen', '4740 Maple Ave, H6S 7G6, Canada');
INSERT INTO customer VALUES('hope.glover@yahoo.ca', 'Hope Glover', '7650 Cedar St, L1L 8Y3, Canada');
INSERT INTO customer VALUES('mack.rowe@yahoo.ca', 'Mack Rowe', '557 Richmond Ave, T0Z 3V6, Canada');
INSERT INTO customer VALUES('matilda.cook@gmail.com', 'Matilda Cook', '7201 Dalhousie Ave, I6Q 1K8, Canada');
INSERT INTO customer VALUES('ezekiel.eaton@gmail.com', 'Ezekiel Eaton', '2542 Lake of Bays Road, L1S 6D2, Canada');
INSERT INTO customer VALUES('miley.patel@yahoo.ca', 'Miley Patel', '4967 College Ave, C4N 3X3, Canada');
INSERT INTO customer VALUES('parker.hubbard@gmail.com', 'Parker Hubbard', '4538 Grand Marais Ave, N5R 3K8, Canada');
INSERT INTO customer VALUES('rosie.mayo@gmail.com', 'Rosie Mayo', '5221 3rd St, G9U 2E9, Canada');
INSERT INTO customer VALUES('jericho.jordan@yahoo.ca', 'Jericho Jordan', '3376 Richmond Ave, N3Y 7A1, Canada');
INSERT INTO customer VALUES('adalynn.woodard@hotmail.com', 'Adalynn Woodard', '9207 College Ave, W0P 3T9, Canada');
INSERT INTO customer VALUES('westley.gilbert@gmail.com', 'Westley Gilbert', '3975 Maple Ave, B9G 2E9, Canada');
INSERT INTO customer VALUES('jocelyn.mosley@hotmail.com', 'Jocelyn Mosley', '3958 Pine Rd, T2F 8B4, Canada');
INSERT INTO customer VALUES('rayden.valenzuela@gmail.com', 'Rayden Valenzuela', '8349 Lakeview Ave, Y4A 7C0, Canada');
INSERT INTO customer VALUES('henley.singh@yahoo.ca', 'Henley Singh', '9833 Arctic Way, Y5O 6P7, Canada');
INSERT INTO customer VALUES('louis.jacobs@yahoo.ca', 'Louis Jacobs', '7016 Lake of Bays Road, W8G 2L6, Canada');
INSERT INTO customer VALUES('camilla.lim@hotmail.com', 'Camilla Lim', '5362 Queen St, M4L 0T5, Canada');
INSERT INTO customer VALUES('cal.middleton@hotmail.com', 'Cal Middleton', '2816 Simcoe St, U7Q 0G9, Canada');
INSERT INTO customer VALUES('madalyn.bailey@hotmail.com', 'Madalyn Bailey', '728 Main St, L1B 0A7, Canada');
INSERT INTO customer VALUES('axel.randolph@yahoo.ca', 'Axel Randolph', '5627 West Ave, I8W 9R6, Canada');
INSERT INTO customer VALUES('kailey.brewer@gmail.com', 'Kailey Brewer', '3430 Dalhousie Ave, A8N 8Z5, Canada');
INSERT INTO customer VALUES('cruz.pugh@gmail.com', 'Cruz Pugh', '5514 Wellington St, A1J 9Q3, Canada');
INSERT INTO customer VALUES('landry.murphy@hotmail.com', 'Landry Murphy', '7587 Victoria Ave, L3D 7O0, Canada');
INSERT INTO customer VALUES('cameron.blanchard@yahoo.ca', 'Cameron Blanchard', '3081 Brock Rd, J0D 9H7, Canada');
INSERT INTO customer VALUES('layne.lam@gmail.com', 'Layne Lam', '6618 Richmond Ave, X2H 2M4, Canada');
INSERT INTO customer VALUES('bodie.wright@yahoo.ca', 'Bodie Wright', '1573 Pierre Ave, H2M 3J4, Canada');
INSERT INTO customer VALUES('lily.walsh@yahoo.ca', 'Lily Walsh', '6110 Dundas Rd, A4W 8Q8, Canada');
INSERT INTO customer VALUES('bodhi.cortes@gmail.com', 'Bodhi Cortes', '3345 Alfred St, S0N 5H8, Canada');
INSERT INTO customer VALUES('lea.hayes@yahoo.ca', 'Lea Hayes', '4015 Main St, H4P 5J3, Canada');
INSERT INTO customer VALUES('legend.blackwell@hotmail.com', 'Legend Blackwell', '9046 Lakeview Ave, G0E 9C8, Canada');
INSERT INTO customer VALUES('saoirse.foley@yahoo.ca', 'Saoirse Foley', '4025 Vimy St, G7N 9P9, Canada');
INSERT INTO customer VALUES('mohammad.wagner@yahoo.ca', 'Mohammad Wagner', '4835 Main St, B8L 2L4, Canada');
INSERT INTO customer VALUES('maeve.potts@yahoo.ca', 'Maeve Potts', '4410 Stanley Way, Y0X 8F2, Canada');
INSERT INTO customer VALUES('alfred.dudley@gmail.com', 'Alfred Dudley', '2520 Duke St, Q7K 3B9, Canada');
INSERT INTO customer VALUES('hadleigh.mcmahon@yahoo.ca', 'Hadleigh McMahon', '6435 Stanley Way, K8K 3A4, Canada');
INSERT INTO customer VALUES('jakob.poole@gmail.com', 'Jakob Poole', '8354 20th Ave, P1L 1P9, Canada');
INSERT INTO customer VALUES('bonnie.fitzpatrick@hotmail.com', 'Bonnie Fitzpatrick', '702 Dundas Rd, D5A 4C9, Canada');
INSERT INTO customer VALUES('blaze.dodson@gmail.com', 'Blaze Dodson', '8629 20th Ave, Y6J 6U8, Canada');
INSERT INTO customer VALUES('etta.roberts@gmail.com', 'Etta Roberts', '7215 York St, O4K 1N1, Canada');
INSERT INTO customer VALUES('josiah.fuentes@gmail.com', 'Josiah Fuentes', '9734 Argyle St, Z2G 0I1, Canada');
INSERT INTO customer VALUES('madeleine.bradley@yahoo.ca', 'Madeleine Bradley', '9979 Richmond Ave, X0C 5P3, Canada');
INSERT INTO customer VALUES('richard.harding@yahoo.ca', 'Richard Harding', '6884 Park Rd, C5W 2T9, Canada');
INSERT INTO customer VALUES('aniya.shields@gmail.com', 'Aniya Shields', '5283 Queen St, C0Y 7C1, Canada');
INSERT INTO customer VALUES('devon.frye@yahoo.ca', 'Devon Frye', '8452 Vimy St, F2S 6X9, Canada');
INSERT INTO customer VALUES('raya.burch@hotmail.com', 'Raya Burch', '39 George St, D6L 1I1, Canada');
INSERT INTO customer VALUES('gerald.mccall@yahoo.ca', 'Gerald McCall', '2220 Queen St, O7H 4R1, Canada');
INSERT INTO customer VALUES('kai.townsend@hotmail.com', 'Kai Townsend', '8044 Coastal Highway, N2K 2T0, Canada');
INSERT INTO customer VALUES('alexis.villanueva@hotmail.com', 'Alexis Villanueva', '7103 Brock Rd, P7B 6L8, Canada');
INSERT INTO customer VALUES('monroe.escobar@yahoo.ca', 'Monroe Escobar', '7854 Tecumseh Rd, Y4J 3M2, Canada');
INSERT INTO customer VALUES('zachariah.hudson@gmail.com', 'Zachariah Hudson', '9471 Frederick Ave, P9Z 3C2, Canada');
INSERT INTO customer VALUES('kamila.simon@gmail.com', 'Kamila Simon', '7079 Regent Ave, I4G 3G5, Canada');
INSERT INTO customer VALUES('zayne.corona@hotmail.com', 'Zayne Corona', '1633 Concession Road 6, Q7O 7F7, Canada');
INSERT INTO customer VALUES('marianna.meyers@gmail.com', 'Marianna Meyers', '1617 Peel St, R2W 2E7, Canada');
INSERT INTO customer VALUES('julien.lozano@yahoo.ca', 'Julien Lozano', '665 Grand Ave, T6K 6Q9, Canada');
INSERT INTO customer VALUES('cecelia.fitzgerald@yahoo.ca', 'Cecelia Fitzgerald', '6180 Parliament St, O1D 1P6, Canada');
INSERT INTO customer VALUES('peyton.hickman@yahoo.ca', 'Peyton Hickman', '1357 Peel St, N6Y 6J0, Canada');
INSERT INTO customer VALUES('scarlette.mendez@hotmail.com', 'Scarlette Mendez', '2781 Grand Ave, M0S 4K9, Canada');
INSERT INTO customer VALUES('arthur.west@gmail.com', 'Arthur West', '4447 Parliament St, N9T 4D6, Canada');
INSERT INTO customer VALUES('remi.schaefer@yahoo.ca', 'Remi Schaefer', '7830 Arctic Way, D7U 3U5, Canada');
INSERT INTO customer VALUES('ishaan.bender@gmail.com', 'Ishaan Bender', '5481 9th St, P2C 7Q0, Canada');
INSERT INTO customer VALUES('lilyana.curry@yahoo.ca', 'Lilyana Curry', '4335 George St, T4A 7A8, Canada');
INSERT INTO customer VALUES('briggs.giles@hotmail.com', 'Briggs Giles', '2425 Concession Road 23, E9O 3Y4, Canada');
INSERT INTO customer VALUES('bailee.cross@yahoo.ca', 'Bailee Cross', '5136 Park Rd, O7Z 8U8, Canada');
INSERT INTO customer VALUES('fabian.barry@yahoo.ca', 'Fabian Barry', '3305 3rd St, C6M 2E6, Canada');
INSERT INTO customer VALUES('waverly.xiong@hotmail.com', 'Waverly Xiong', '592 Queen St, M3X 0V0, Canada');
INSERT INTO customer VALUES('azrael.farrell@gmail.com', 'Azrael Farrell', '2623 Cedar St, O2X 3D5, Canada');
INSERT INTO customer VALUES('kassidy.barton@yahoo.ca', 'Kassidy Barton', '4129 3rd St, T2Z 1O9, Canada');
INSERT INTO customer VALUES('cassius.knight@yahoo.ca', 'Cassius Knight', '7855 Regent Ave, O2E 4V9, Canada');
INSERT INTO customer VALUES('gracie.reid@hotmail.com', 'Gracie Reid', '4438 College Ave, T9H 4F5, Canada');
INSERT INTO customer VALUES('josue.allison@gmail.com', 'Josue Allison', '2259 Argyle St, W2P 3G0, Canada');
INSERT INTO customer VALUES('chelsea.reed@gmail.com', 'Chelsea Reed', '8901 Balmoral St, G2I 7N9, Canada');
INSERT INTO customer VALUES('easton.atkins@gmail.com', 'Easton Atkins', '6481 9th St, G7T 9I3, Canada');
INSERT INTO customer VALUES('mina.harrell@gmail.com', 'Mina Harrell', '7221 Pine Rd, E8C 4X2, Canada');
INSERT INTO customer VALUES('nelson.durham@gmail.com', 'Nelson Durham', '4683 Elgin St, U3O 2N7, Canada');
INSERT INTO customer VALUES('tiffany.moreno@gmail.com', 'Tiffany Moreno', '4537 Richmond Ave, E0A 3Z9, Canada');
INSERT INTO customer VALUES('myles.jimenez@yahoo.ca', 'Myles Jimenez', '6520 Lake of Bays Road, L4Q 9Y9, Canada');
INSERT INTO customer VALUES('adeline.houston@yahoo.ca', 'Adeline Houston', '4704 Victoria Ave, T7C 4H1, Canada');
INSERT INTO customer VALUES('sylas.elliott@gmail.com', 'Sylas Elliott', '1066 Dundas Rd, M7U 8A4, Canada');
INSERT INTO customer VALUES('noelle.conrad@gmail.com', 'Noelle Conrad', '5917 Grand Marais Ave, A8L 3M7, Canada');
INSERT INTO customer VALUES('dilan.larson@gmail.com', 'Dilan Larson', '8011 Bay Ave, O6G 9Y4, Canada');
INSERT INTO customer VALUES('alayna.barr@hotmail.com', 'Alayna Barr', '1147 Wellington St, B2C 1E1, Canada');
INSERT INTO customer VALUES('harley.hudson@hotmail.com', 'Harley Hudson', '4231 Oak St, R0W 8R6, Canada');
INSERT INTO customer VALUES('kamila.suarez@hotmail.com', 'Kamila Suarez', '8915 Simcoe St, M1V 4D2, Canada');
INSERT INTO customer VALUES('soren.coffey@gmail.com', 'Soren Coffey', '5784 Duke St, S4R 9C2, Canada');
INSERT INTO customer VALUES('paola.o’neill@yahoo.ca', 'Paola O’Neill', '262 Dieppe Ave, Z9Z 1V5, Canada');
INSERT INTO customer VALUES('marcel.brady@yahoo.ca', 'Marcel Brady', '4396 Richmond Ave, X2N 2V4, Canada');
INSERT INTO customer VALUES('ryan.wheeler@yahoo.ca', 'Ryan Wheeler', '9751 Coastal Highway, G2R 3J9, Canada');
INSERT INTO customer VALUES('kenneth.rice@yahoo.ca', 'Kenneth Rice', '6606 Concession Road 23, H1W 7V5, Canada');
INSERT INTO customer VALUES('ada.murray@yahoo.ca', 'Ada Murray', '3035 Frederick Ave, L2T 5F2, Canada');
INSERT INTO customer VALUES('ashton.carroll@yahoo.ca', 'Ashton Carroll', '8837 Wellington St, U7S 2S3, Canada');
INSERT INTO customer VALUES('zara.cummings@gmail.com', 'Zara Cummings', '5521 Duke St, F7Z 4X4, Canada');
INSERT INTO customer VALUES('raiden.bean@gmail.com', 'Raiden Bean', '968 Charles St, A6P 8S8, Canada');
INSERT INTO customer VALUES('jenesis.farley@gmail.com', 'Jenesis Farley', '3567 Wellington St, B2I 7S0, Canada');
INSERT INTO customer VALUES('graysen.glover@hotmail.com', 'Graysen Glover', '8800 22nd Ave, N9H 0G4, Canada');
INSERT INTO customer VALUES('alessia.scott@hotmail.com', 'Alessia Scott', '360 Lakeview Ave, T7X 1P5, Canada');
INSERT INTO customer VALUES('leo.villanueva@gmail.com', 'Leo Villanueva', '5360 Tecumseh Rd, O7Q 0I9, Canada');
INSERT INTO customer VALUES('monroe.reese@yahoo.ca', 'Monroe Reese', '3801 Dalhousie Ave, Y0D 3T0, Canada');
INSERT INTO customer VALUES('alijah.zavala@hotmail.com', 'Alijah Zavala', '4994 St. Lawrence Ave, T7F 0Z1, Canada');
INSERT INTO customer VALUES('liv.jennings@gmail.com', 'Liv Jennings', '5285 Coastal Highway, B2M 5Q2, Canada');
INSERT INTO customer VALUES('corbin.hobbs@hotmail.com', 'Corbin Hobbs', '2845 9th St, W7D 7H8, Canada');
INSERT INTO customer VALUES('lacey.gregory@gmail.com', 'Lacey Gregory', '9577 King St, R3B 3K6, Canada');
INSERT INTO customer VALUES('travis.hamilton@yahoo.ca', 'Travis Hamilton', '1722 Charles St, J2I 7S1, Canada');
INSERT INTO customer VALUES('mackenzie.harmon@gmail.com', 'Mackenzie Harmon', '8105 Grand Ave, I1K 1V6, Canada');
INSERT INTO customer VALUES('roberto.leach@gmail.com', 'Roberto Leach', '3120 Disputed Rd, C4V 1N9, Canada');
INSERT INTO customer VALUES('martha.mejia@gmail.com', 'Martha Mejia', '5536 St. Lawrence Ave, X8K 3G7, Canada');
INSERT INTO customer VALUES('atticus.carrillo@gmail.com', 'Atticus Carrillo', '8922 Maple Ave, Q4C 8B9, Canada');
INSERT INTO customer VALUES('kaylani.davidson@yahoo.ca', 'Kaylani Davidson', '6179 Simcoe St, O2D 6O6, Canada');
INSERT INTO customer VALUES('dante.reynolds@hotmail.com', 'Dante Reynolds', '771 Dalhousie Ave, D1X 0H9, Canada');
INSERT INTO customer VALUES('isabelle.cabrera@yahoo.ca', 'Isabelle Cabrera', '2144 20th Ave, V3R 3N5, Canada');
INSERT INTO customer VALUES('cade.gordon@gmail.com', 'Cade Gordon', '3177 Duke St, U0D 2B5, Canada');
INSERT INTO customer VALUES('taylor.walton@yahoo.ca', 'Taylor Walton', '8068 Tecumseh Rd, Q2V 7Z3, Canada');
INSERT INTO customer VALUES('dominick.schwartz@gmail.com', 'Dominick Schwartz', '5950 Park Rd, L9D 0C7, Canada');
INSERT INTO customer VALUES('lilliana.steele@gmail.com', 'Lilliana Steele', '6717 Dieppe Ave, L0S 6Q7, Canada');
INSERT INTO customer VALUES('elian.doyle@yahoo.ca', 'Elian Doyle', '6445 St. Catherine St, X9G 7K8, Canada');
INSERT INTO customer VALUES('annalise.garner@hotmail.com', 'Annalise Garner', '1724 Richmond Ave, O4L 5S2, Canada');
INSERT INTO customer VALUES('sage.lawrence@hotmail.com', 'Sage Lawrence', '9197 St. Catherine St, Q6E 1R8, Canada');
INSERT INTO customer VALUES('lauren.cabrera@gmail.com', 'Lauren Cabrera', '5661 St. Catherine St, N3H 1S4, Canada');
INSERT INTO customer VALUES('cade.salgado@gmail.com', 'Cade Salgado', '1615 Wellington St, D2K 9E0, Canada');
INSERT INTO customer VALUES('avalynn.chen@hotmail.com', 'Avalynn Chen', '8114 Oak St, Q9L 8K2, Canada');
INSERT INTO customer VALUES('emmanuel.frederick@hotmail.com', 'Emmanuel Frederick', '1346 20th Ave, H3U 4R8, Canada');
INSERT INTO customer VALUES('sariyah.hardin@gmail.com', 'Sariyah Hardin', '807 Main St, G0U 6H6, Canada');
INSERT INTO customer VALUES('hassan.paul@gmail.com', 'Hassan Paul', '1734 Victoria Ave, P7Y 7N6, Canada');
INSERT INTO customer VALUES('daphne.howard@yahoo.ca', 'Daphne Howard', '1556 Richmond Ave, H9K 4X5, Canada');
INSERT INTO customer VALUES('jeremiah.valdez@hotmail.com', 'Jeremiah Valdez', '229 York St, Y9T 4C8, Canada');
INSERT INTO customer VALUES('diana.espinoza@yahoo.ca', 'Diana Espinoza', '4735 St. Lawrence Ave, I5Q 7R6, Canada');
INSERT INTO customer VALUES('dallas.hendricks@yahoo.ca', 'Dallas Hendricks', '1036 Pierre Ave, V0R 9U9, Canada');
INSERT INTO customer VALUES('dani.duffy@gmail.com', 'Dani Duffy', '7422 College Ave, J6T 1B5, Canada');
INSERT INTO customer VALUES('kyng.mcgee@hotmail.com', 'Kyng McGee', '6277 Cedar St, N5I 4H5, Canada');
INSERT INTO customer VALUES('kayleigh.harris@gmail.com', 'Kayleigh Harris', '7968 Dufferin St, U6L 0N5, Canada');
INSERT INTO customer VALUES('samuel.mason@yahoo.ca', 'Samuel Mason', '621 St. Catherine St, K5R 5P6, Canada');
INSERT INTO customer VALUES('sienna.farmer@gmail.com', 'Sienna Farmer', '5026 Oak St, D6K 4J4, Canada');
INSERT INTO customer VALUES('jamison.castaneda@yahoo.ca', 'Jamison Castaneda', '230 Stanley Way, S8Y 9P2, Canada');
INSERT INTO customer VALUES('keira.meadows@yahoo.ca', 'Keira Meadows', '9022 Main St, I7R 8S6, Canada');
INSERT INTO customer VALUES('wayne.hunter@gmail.com', 'Wayne Hunter', '1735 Grand Marais Ave, Q5F 4A2, Canada');
INSERT INTO customer VALUES('khloe.ho@gmail.com', 'Khloe Ho', '9265 Dalhousie Ave, I4B 9H9, Canada');
INSERT INTO customer VALUES('morgan.figueroa@hotmail.com', 'Morgan Figueroa', '7303 20th Ave, H4H 1Y3, Canada');
INSERT INTO customer VALUES('lilith.anderson@gmail.com', 'Lilith Anderson', '5603 Grand Marais Ave, F2V 6E5, Canada');
INSERT INTO customer VALUES('jacob.carey@yahoo.ca', 'Jacob Carey', '3991 Dieppe Ave, I6S 1A1, Canada');
INSERT INTO customer VALUES('alora.hansen@gmail.com', 'Alora Hansen', '6096 Queen St, I6C 8R5, Canada');
INSERT INTO customer VALUES('charlie.hardin@gmail.com', 'Charlie Hardin', '6512 Concession Road 6, X0N 2R3, Canada');
INSERT INTO customer VALUES('vada.solomon@gmail.com', 'Vada Solomon', '260 College Ave, B5Q 9X7, Canada');
INSERT INTO customer VALUES('musa.herring@yahoo.ca', 'Musa Herring', '5552 Arctic Way, T0J 2D7, Canada');
INSERT INTO customer VALUES('denver.rich@hotmail.com', 'Denver Rich', '8051 Tecumseh Rd, O5E 1Q0, Canada');
INSERT INTO customer VALUES('miller.cabrera@yahoo.ca', 'Miller Cabrera', '2341 Arctic Way, L1E 2C3, Canada');
INSERT INTO customer VALUES('daleyza.booker@hotmail.com', 'Daleyza Booker', '8291 Lake of Bays Road, T0Q 1H8, Canada');
INSERT INTO customer VALUES('dominik.cox@yahoo.ca', 'Dominik Cox', '9317 3rd St, W9A 0T7, Canada');
INSERT INTO customer VALUES('sadie.moyer@yahoo.ca', 'Sadie Moyer', '1665 Tecumseh Rd, A9Z 0K8, Canada');
INSERT INTO customer VALUES('ahmir.jackson@hotmail.com', 'Ahmir Jackson', '430 St. Lawrence Ave, B7R 0O8, Canada');
INSERT INTO customer VALUES('avery.ray@hotmail.com', 'Avery Ray', '3740 Dieppe Ave, B5R 3S0, Canada');
INSERT INTO customer VALUES('arlo.morse@yahoo.ca', 'Arlo Morse', '1787 Concession Road 23, D0C 1V7, Canada');
INSERT INTO customer VALUES('kairi.pittman@yahoo.ca', 'Kairi Pittman', '3743 York St, S7O 5C5, Canada');
INSERT INTO customer VALUES('valentino.cox@yahoo.ca', 'Valentino Cox', '8862 Pierre Ave, O1M 8K3, Canada');
INSERT INTO customer VALUES('sadie.moran@hotmail.com', 'Sadie Moran', '1164 King St, K2O 0B8, Canada');
INSERT INTO customer VALUES('tate.huynh@gmail.com', 'Tate Huynh', '5596 22nd Ave, F5C 6P9, Canada');
INSERT INTO customer VALUES('oaklee.adams@hotmail.com', 'Oaklee Adams', '7252 Lakeview Ave, R9A 1C5, Canada');
INSERT INTO customer VALUES('hudson.odom@yahoo.ca', 'Hudson Odom', '1792 Dundas Rd, T0P 0H7, Canada');
INSERT INTO customer VALUES('laylani.cobb@yahoo.ca', 'Laylani Cobb', '1770 Lake of Bays Road, F9F 2Q6, Canada');
INSERT INTO customer VALUES('raphael.mccann@yahoo.ca', 'Raphael McCann', '1227 Pierre Ave, A5S 3C1, Canada');
INSERT INTO customer VALUES('joyce.pineda@hotmail.com', 'Joyce Pineda', '2110 Dundas Rd, M3Q 3H7, Canada');
INSERT INTO customer VALUES('gerardo.daniels@hotmail.com', 'Gerardo Daniels', '4614 Maple Ave, F6G 7K6, Canada');
INSERT INTO customer VALUES('ember.sanders@gmail.com', 'Ember Sanders', '4597 Grand Marais Ave, X4S 3M7, Canada');
INSERT INTO customer VALUES('jose.garrison@yahoo.ca', 'Jose Garrison', '5982 King St, P3C 9A8, Canada');
INSERT INTO customer VALUES('cadence.dawson@hotmail.com', 'Cadence Dawson', '3703 Dieppe Ave, S5O 9B6, Canada');
INSERT INTO customer VALUES('iker.griffith@yahoo.ca', 'Iker Griffith', '4040 College Ave, X0Y 9T6, Canada');
INSERT INTO customer VALUES('alicia.castro@yahoo.ca', 'Alicia Castro', '3868 Alfred St, I6U 7Y0, Canada');
INSERT INTO customer VALUES('jasper.tanner@hotmail.com', 'Jasper Tanner', '3687 Maple Ave, Y9W 8Y7, Canada');
INSERT INTO customer VALUES('harmoni.chavez@yahoo.ca', 'Harmoni Chavez', '339 22nd Ave, U1Z 7A8, Canada');
INSERT INTO customer VALUES('ian.lambert@yahoo.ca', 'Ian Lambert', '1082 Duke St, X7M 7F5, Canada');
INSERT INTO customer VALUES('nina.casey@hotmail.com', 'Nina Casey', '7493 Brock Rd, Q8S 6O0, Canada');
INSERT INTO customer VALUES('armando.travis@hotmail.com', 'Armando Travis', '5112 Lakeview Ave, G9J 4R6, Canada');
INSERT INTO customer VALUES('mazikee.bean@gmail.com', 'Mazikee Bean', '6357 Parliament St, U2F 8G9, Canada');
INSERT INTO customer VALUES('mccoy.norman@yahoo.ca', 'Mccoy Norman', '308 Peel St, A5V 9L3, Canada');
INSERT INTO customer VALUES('malani.watts@yahoo.ca', 'Malani Watts', '7256 Main St, C7E 3D3, Canada');
INSERT INTO customer VALUES('dakota.phan@hotmail.com', 'Dakota Phan', '6178 Dalhousie Ave, L8K 3Z4, Canada');
INSERT INTO customer VALUES('elsa.rosales@hotmail.com', 'Elsa Rosales', '9084 Pine Rd, C5B 5H9, Canada');
INSERT INTO customer VALUES('wilder.mack@hotmail.com', 'Wilder Mack', '6993 Oak St, I2E 3Y4, Canada');
INSERT INTO customer VALUES('nadia.ventura@gmail.com', 'Nadia Ventura', '4967 Charles St, E3G 2W0, Canada');
INSERT INTO customer VALUES('branson.chung@yahoo.ca', 'Branson Chung', '5473 Dundas Rd, Q1E 3H1, Canada');
INSERT INTO customer VALUES('rivka.brandt@gmail.com', 'Rivka Brandt', '2047 Lakeview Ave, U3J 7C4, Canada');
INSERT INTO customer VALUES('damir.jenkins@yahoo.ca', 'Damir Jenkins', '6539 St. Lawrence Ave, A1G 3H4, Canada');
INSERT INTO customer VALUES('rylee.conway@gmail.com', 'Rylee Conway', '1082 15th St, T5W 4Y8, Canada');
INSERT INTO customer VALUES('orlando.hoffman@yahoo.ca', 'Orlando Hoffman', '2677 Dufferin St, C2D 1H2, Canada');
INSERT INTO customer VALUES('aspen.sawyer@hotmail.com', 'Aspen Sawyer', '4406 20th Ave, F5J 2O4, Canada');
INSERT INTO customer VALUES('jefferson.donaldson@yahoo.ca', 'Jefferson Donaldson', '359 Maple Ave, D2Y 0O3, Canada');
INSERT INTO customer VALUES('natasha.cain@gmail.com', 'Natasha Cain', '6856 36th Ave, Y0C 9F7, Canada');
INSERT INTO customer VALUES('benson.webster@hotmail.com', 'Benson Webster', '5424 Balmoral St, I0Q 7B7, Canada');
INSERT INTO customer VALUES('kensley.richardson@yahoo.ca', 'Kensley Richardson', '8430 Lake of Bays Road, W7U 9F4, Canada');
INSERT INTO customer VALUES('robert.thornton@gmail.com', 'Robert Thornton', '456 West Ave, Y6R 2J4, Canada');
INSERT INTO customer VALUES('haisley.jacobson@yahoo.ca', 'Haisley Jacobson', '3494 Pine Rd, S4X 8J8, Canada');
INSERT INTO customer VALUES('legacy.vu@hotmail.com', 'Legacy Vu', '7616 Disputed Rd, H7Z 1N7, Canada');
INSERT INTO customer VALUES('kimora.townsend@yahoo.ca', 'Kimora Townsend', '536 Park Rd, E9R 1M7, Canada');
INSERT INTO customer VALUES('alexis.gould@gmail.com', 'Alexis Gould', '2967 Pierre Ave, R4G 0S8, Canada');
INSERT INTO customer VALUES('violeta.carpenter@yahoo.ca', 'Violeta Carpenter', '5813 Frederick Ave, L2J 7D4, Canada');
INSERT INTO customer VALUES('jeremy.knapp@hotmail.com', 'Jeremy Knapp', '1353 Cedar St, X3H 3T5, Canada');
INSERT INTO customer VALUES('linda.delgado@gmail.com', 'Linda Delgado', '2826 Dalhousie Ave, S7A 1Q1, Canada');
INSERT INTO customer VALUES('colt.barnett@hotmail.com', 'Colt Barnett', '9489 Pine Rd, O0N 8C7, Canada');
INSERT INTO customer VALUES('harlow.ponce@yahoo.ca', 'Harlow Ponce', '2755 9th St, V8T 4B1, Canada');
INSERT INTO customer VALUES('langston.castillo@hotmail.com', 'Langston Castillo', '6651 22nd Ave, M8P 8D8, Canada');
INSERT INTO customer VALUES('eva.turner@hotmail.com', 'Eva Turner', '9020 St. Catherine St, R1R 1R7, Canada');
INSERT INTO customer VALUES('joshua.york@hotmail.com', 'Joshua York', '4455 3rd St, M1X 6D9, Canada');
INSERT INTO customer VALUES('milan.rivera@gmail.com', 'Milan Rivera', '9405 Alfred St, O2Z 8Q5, Canada');
INSERT INTO customer VALUES('charles.atkins@hotmail.com', 'Charles Atkins', '4084 Pierre Ave, D5L 7Q9, Canada');
INSERT INTO customer VALUES('mina.kelly@hotmail.com', 'Mina Kelly', '1961 9th St, C8L 4N6, Canada');
INSERT INTO customer VALUES('cooper.molina@hotmail.com', 'Cooper Molina', '1007 Lakeview Ave, A2Y 9P8, Canada');
INSERT INTO customer VALUES('alexandria.castaneda@hotmail.com', 'Alexandria Castaneda', '3325 3rd St, V3M 7G1, Canada');
INSERT INTO customer VALUES('collin.magana@gmail.com', 'Collin Magana', '2722 Concession Road 23, W6F 7Q6, Canada');
INSERT INTO customer VALUES('amaris.adkins@hotmail.com', 'Amaris Adkins', '6315 Grand Ave, L8K 3K8, Canada');
INSERT INTO customer VALUES('kylo.mcdowell@yahoo.ca', 'Kylo McDowell', '7888 Lake of Bays Road, J1E 7O1, Canada');
INSERT INTO customer VALUES('rayna.cardenas@hotmail.com', 'Rayna Cardenas', '7231 36th Ave, D7U 8E4, Canada');
INSERT INTO customer VALUES('johnathan.blackburn@gmail.com', 'Johnathan Blackburn', '4984 Pine Rd, E3A 9O4, Canada');
INSERT INTO customer VALUES('frida.curtis@hotmail.com', 'Frida Curtis', '5791 Lakeview Ave, S0W 3C9, Canada');
INSERT INTO customer VALUES('muhammad.horton@hotmail.com', 'Muhammad Horton', '5789 York St, U8B 0F4, Canada');
